### ISSUE TITLE
Another issue with pg_stat_activity 

### ISSUE THREAD

**Issue by bilbolodz** [Spindel/PgZabbix#2]
I've found another incompatibility with pg_stat_activity table:

`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/__main__.py", line 4, in <module>
  File "/pgzabbix/cmd.py", line 59, in main
    prototypes that will later be wrapped in a more sophisticated interface.
  File "/pgzabbix/__init__.py", line 35, in all_generic
  File "/pgzabbix/generic.py", line 33, in psql_active_connections
psycopg2.ProgrammingError: column "state" does not exist
LINE 1: select count(*) from pg_stat_activity where state = 'active'
` 
Problem observed on version: 9.1.9, 9.1.10, 9.1.12
What more do you need to deal with these issue?

**Comment by Spindel** [comment]
9.1 wow. Is that even supported by upstream anymore?

Either way, I’ll try it out when I’m back from vacation if I can find a working container with 9.1 for it. 

Thank you for the report. 

On mobile, please excuse my brevity.

**Comment by bilbolodz** [comment]
> 9.1 wow. Is that even supported by upstream anymore?
Sorry for that but it is..... It's working on closed internal network but it STILL is working. There are plans to replaced it but.......... maybe in next century ;-)
Any way it has to be monitored....

Waiting for result and happy vacation.

**Comment by bilbolodz** [comment]
How is going on your vacation? ;-)

**Comment by Spindel** [comment]
Can you give the branch here a try and see if that works for you?


https://github.com/Spindel/PgZabbix/pull/6

**Comment by bilbolodz** [comment]
postgres-91 branch is working fine (at least at PostgreSQL 9.1.9)

**Comment by bilbolodz** [comment]
Should I wait to "final solution" or use code from branch?

**Comment by Spindel** [comment]
I'm just going to bump the version number and merge that, so you're good with either.
