### ISSUE TITLE
Problem runnig pgzabbix on Ubuntu 10.04 (python problem)

### ISSUE THREAD

**Issue by bilbolodz** [Spindel/PgZabbix#3]
When trying to run pgzabbix on Ubuntu 10.04.4 I'm getting an error:

'
crw:~# /usr/bin/python /usr/local/lib/pgzabbix-1.7.linux-x86_64.zip --read
Traceback (most recent call last):
  File "/usr/lib/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/usr/local/lib/pgzabbix-1.7.linux-x86_64.zip/__main__.py", line 4, in <module>
  File "/usr/local/lib/pgzabbix-1.7.linux-x86_64.zip/pgzabbix/cmd.py", line 55, in main
    class Cmd:
  File "/usr/local/lib/pgzabbix-1.7.linux-x86_64.zip/pgzabbix/cmd.py", line 27, in get_connection
    is no do_ method.
AttributeError: 'module' object has no attribute \'extensions\'
'

**Comment by Spindel** [comment]
That's a problem with an old (or ancient?) version of psycopg2, the underlying python/postgres connector.

Sadly, as a hobby, I'm not going to resurrect a 9 year old OS and port a code base to it, that's the kind of drudge-work I'd bill someone for.

I'll gladly welcome patches for it. Otherwise, if it's a real problem, you can run the monitoring (pgzabbix) on another machine and connect to  the PostgreSQL server over the network.

**Comment by bilbolodz** [comment]
It's 2.0.13 version. I will try to look into it.

**Comment by bilbolodz** [comment]
It's NOT working on 2.7 and above. It's working on 2.6.2.

**Comment by Spindel** [comment]
Oh, It's broken with Psycopg 2.7? 

I'll have to fix that then!

**Comment by bilbolodz** [comment]
Sorry my mistake, hold on.

**Comment by bilbolodz** [comment]
OK, now I remember and I will try to be more precise:
Not working on: 2.0.13 (version "shipped" with OS).
I've tried to compile never version and it tuned out that 2.7 and above require  postgreSQL client library version from 9.1, which was available in that OS.
Luckily version 2.6.2 require lower client version and your software is working with it, so solution for Ubuntu 10.04 is: compile and install manually psycopg 2.6.2. You don't have to do anything with it. I hope it's clear now.

**Comment by Spindel** [comment]
Oh, that makes more sense.

Before 2.x something there wasn't an option to easily get the version of
the Postgres server from the library.  ( I guess I could in theory replace
that check with a select for the pg version, instead).  Then I'll leave
this as closed.

Good you got a solution!
