### ISSUE TITLE
Problem runnig pgzabbix on Ubuntu 10.10 (postgres problem) 

### ISSUE THREAD

**Issue by bilbolodz** [Spindel/PgZabbix#5]
When I'm trying to run pgzabbix on Ubuntu 10.10 I'm getting an error:

root@mpi:~# /usr/bin/python /usr/local/lib/pgzabbix-1.7.linux-x86_64.zip --read
\- psql.running 1
Traceback (most recent call last):
  File "/usr/lib/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/usr/local/lib/pgzabbix-1.7.linux-x86_64.zip/__main__.py", line 4, in <module>
  File "/usr/local/lib/pgzabbix-1.7.linux-x86_64.zip/pgzabbix/cmd.py", line 59, in main
    prototypes that will later be wrapped in a more sophisticated interface.
  File "/usr/local/lib/pgzabbix-1.7.linux-x86_64.zip/pgzabbix/__init__.py", line 35, in all_generic
  File "/usr/local/lib/pgzabbix-1.7.linux-x86_64.zip/pgzabbix/generic.py", line 149, in machine_is_primary
psycopg2.ProgrammingError: function pg_is_in_recovery() does not exist
LINE 1: select (NOT(pg_is_in_recovery()))::int
                    ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

During creating view I've got an error:

`ERROR:  type "pg_catalog.pg_stat_replication" does not exist
ERROR:  function pg_stat_repl() does not exist
LINE 1: CREATE VIEW public.pg_stat_repl AS SELECT * FROM pg_stat_rep...
                                                         ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
ERROR:  relation "public.pg_stat_repl" does not exist`

**Comment by Spindel** [comment]
This looks lrather like a problem against that version of postgres, as it's a :
ProgrammingError: function pg_is_in_recovery

How old is this Postgres that you're running against?

**Comment by bilbolodz** [comment]
PostgreSQL 8.4.7

**Comment by Spindel** [comment]
Okay, I'm going to leave  8.4 as legacy,  You're welcome to support it and I'll take patches for it, but it's on the far edge of where I'm willing to hack code for as a volunteer.
